export const COVERAGE_FIELDS = {
  'Common Declarations': [
    { id: 'cd-h1', label: 'Named Insured & Address', isHeader: true },
    { id: 'cd-1', label: 'Named Insured' },
    { id: 'cd-2', label: 'Mailing Address' },
    { id: 'cd-h2', label: 'Policy Information', isHeader: true },
    { id: 'cd-3', label: 'Policy Number' },
    { id: 'cd-4', label: 'Policy Effective Date' },
    { id: 'cd-5', label: 'Policy Expiration Date' },
    { id: 'cd-6', label: 'Business Description' },
    { id: 'cd-7', label: 'Carrier / Insurance Company' },
    { id: 'cd-8', label: 'Total Policy Premium' },
  ],
  'General Liability': [
    { id: 'gl-h1', label: 'General Liability Declarations', isHeader: true },
    { id: 'gl-1', label: 'Occurrence Limit' },
    { id: 'gl-2', label: 'General Aggregate Limit' },
    { id: 'gl-3', label: 'Products-Completed Ops Aggregate' },
    { id: 'gl-4', label: 'Personal & Advertising Injury' },
    { id: 'gl-5', label: 'Damage to Premises Rented' },
    { id: 'gl-h2', label: 'Endorsements', isHeader: true },
    { id: 'gl-6', label: 'Additional Insureds' },
    { id: 'gl-7', label: 'Waiver of Subrogation' },
    { id: 'gl-8', label: 'Primary & Non-Contributory' },
    { id: 'gl-9', label: 'GL Premium' },
  ],
  'Commercial Auto': [
    { id: 'ca-h1', label: 'Auto Declarations', isHeader: true },
    { id: 'ca-1', label: 'Liability Limit (CSL)' },
    { id: 'ca-2', label: 'Medical Payments' },
    { id: 'ca-3', label: 'Comprehensive Deductible' },
    { id: 'ca-4', label: 'Collision Deductible' },
    { id: 'ca-h2', label: 'Schedule of Vehicles', isHeader: true },
    { id: 'ca-5', label: 'Year / Make / Model' },
    { id: 'ca-6', label: 'Garaging Address' },
    { id: 'ca-7', label: 'CA Premium' },
  ],
  "Workers' Compensation": [
    { id: 'wc-h1', label: "Workers' Compensation Declarations", isHeader: true },
    { id: 'wc-1', label: 'State(s) of Coverage' },
    { id: 'wc-2', label: 'Employers Liability - Each Accident' },
    { id: 'wc-3', label: 'Employers Liability - Disease (Policy)' },
    { id: 'wc-4', label: 'Employers Liability - Disease (Each Emp)' },
    { id: 'wc-5', label: 'Experience Modification Factor' },
    { id: 'wc-6', label: 'Officers Included/Excluded' },
    { id: 'wc-7', label: 'WC Premium' },
  ],
  'Commercial Property': [
    { id: 'cp-h1', label: 'Property Declarations', isHeader: true },
    { id: 'cp-1', label: 'Location Address' },
    { id: 'cp-2', label: 'Building Limit' },
    { id: 'cp-3', label: 'Business Personal Property Limit' },
    { id: 'cp-4', label: 'Deductible' },
    { id: 'cp-h2', label: 'Business Income', isHeader: true },
    { id: 'cp-5', label: 'BI Limit' },
    { id: 'cp-6', label: 'BI Coinsurance' },
    { id: 'cp-7', label: 'CP Premium' },
  ],
  'Umbrella / Excess': [
    { id: 'umb-h1', label: 'Umbrella Declarations', isHeader: true },
    { id: 'umb-1', label: 'Each Occurrence Limit' },
    { id: 'umb-2', label: 'Aggregate Limit' },
    { id: 'umb-3', label: 'Retained Limit / SIR' },
    { id: 'umb-4', label: 'Umbrella Premium' },
  ],
  'Professional Liability / E&O': [
    { id: 'eo-h1', label: 'E&O Declarations', isHeader: true },
    { id: 'eo-1', label: 'Each Claim Limit' },
    { id: 'eo-2', label: 'Aggregate Limit' },
    { id: 'eo-3', label: 'Retroactive Date' },
    { id: 'eo-4', label: 'Deductible' },
    { id: 'eo-5', label: 'E&O Premium' },
  ],
  'Cyber Liability': [
    { id: 'cy-h1', label: 'Cyber Declarations', isHeader: true },
    { id: 'cy-1', label: 'First Party Coverage Limit' },
    { id: 'cy-2', label: 'Third Party Liability Limit' },
    { id: 'cy-3', label: 'Ransomware / Extortion Limit' },
    { id: 'cy-4', label: 'Deductible' },
    { id: 'cy-5', label: 'Retroactive Date' },
    { id: 'cy-6', label: 'Cyber Premium' },
  ],
  "Directors & Officers (D&O)": [
    { id: 'do-h1', label: 'D&O Declarations', isHeader: true },
    { id: 'do-1', label: 'Limit of Liability' },
    { id: 'do-2', label: 'Retention (Individual)' },
    { id: 'do-3', label: 'Retention (Corporate)' },
    { id: 'do-4', label: 'Retroactive Date' },
    { id: 'do-5', label: 'D&O Premium' },
  ],
  'Crime / Fidelity': [
    { id: 'cr-h1', label: 'Crime Declarations', isHeader: true },
    { id: 'cr-1', label: 'Employee Dishonesty Limit' },
    { id: 'cr-2', label: 'Computer Fraud Limit' },
    { id: 'cr-3', label: 'Funds Transfer Fraud Limit' },
    { id: 'cr-4', label: 'Deductible' },
    { id: 'cr-5', label: 'Crime Premium' },
  ],
  'Employment Practices Liability': [
    { id: 'ep-h1', label: 'EPLI Declarations', isHeader: true },
    { id: 'ep-1', label: 'Each Claim Limit' },
    { id: 'ep-2', label: 'Aggregate Limit' },
    { id: 'ep-3', label: 'Retention' },
    { id: 'ep-4', label: 'Retroactive Date' },
    { id: 'ep-5', label: 'EPLI Premium' },
  ],
  'Inland Marine': [
    { id: 'im-h1', label: 'Inland Marine Declarations', isHeader: true },
    { id: 'im-1', label: 'Coverage Type' },
    { id: 'im-2', label: 'Limit of Insurance' },
    { id: 'im-3', label: 'Deductible' },
    { id: 'im-4', label: 'IM Premium' },
  ],
}
